services:
  db:
    container_name: area_database
    hostname: area_database
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=${ROOT_PASSWORD}
      - MYSQL_DATABASE=${DATABASE}
    volumes:
      - ./Db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "3306:3306"
  backend:
    container_name: area_backend
    build:
      context: ./Api
      dockerfile: Dockerfile
    ports:
      - "8081:3333"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - ./Api/images:/usr/src/app/public/images
    depends_on:
      - frontend
  frontend:
    container_name: area_front
    # image: front_web
    build:
     context: ./front_web
     dockerfile: Dockerfile
    ports:
      - "8080:3000"
    volumes:
      - './front_web:/app'
      - '/app/node_modules'
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - db