services:
  area_database:
    container_name: area_database
    hostname: area_database
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=${ROOT_PASSWORD}
      - MYSQL_DATABASE=${DATABASE}
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "3310:3306"
    networks:
      - personal-network

networks:
  personal-network:
    external: true